server:
  port: 8004

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/Sensa_Notification_Service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
    topics:
      notifications:
        email: email-notification
        sms: sms-notification
      producer:
        delivery: message-delivery-service

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

services:
  template-service:
    url: http://localhost:8003