version: '3.8'

services:
  discovery-service:
    build: .
    image: discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"

    networks:
      - discovery-net

networks:
  discovery-net:
    driver: bridge
