server:
  port: 8003

spring:
  application:
    name: template-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Sensa_Template_Service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

  jpa:
    hibernate:
      ddl-auto: validate
