version: '3.8'

services:
  # --- Authentication-service ---
  authentication-service:
    build: .
    image: authentication-service:latest
    container_name: authentication-service
    ports:
      - "8081:8081"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 28859013

      REDIS_HOST: redis-10595.c61.us-east-1-3.ec2.redns.redis-cloud.com
      REDIS_PORT: "10595"
      REDIS_PASSWORD: PzeBCBpdiPxyOworzHhOkkJzSea38Ilr

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://my-eureka-server-host:8761/eureka"

      # JWT
      JWT_USER_SECRET: "change-me"
      JWT_USER_SECRET_LIFETIME: "3600"

    depends_on:
      - postgres
      - zookeeper
      - kafka
    networks:
      - sensa-network


  # --- PostgreSQL ---
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_DB: Sensa_Authentication_Service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 28859013
    ports:
      - "5432:5432"
    networks:
      - sensa-network


  # --- ZooKeeper ---
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - sensa-network


  # --- Kafka ---
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - sensa-network


networks:
  sensa-network:
    driver: bridge
