spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:postgresql://localhost:5432/Sensa_Authentication_Service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: authentication-service

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml

server:
  port: 8081


jwt:
  user_secret: ${JWT_USER_SECRET}
  user_secret_lifetime: ${JWT_USER_SECRET_LIFETIME}