version: '3.8'

services:
  # --- user-management-service ---
  user-management-service:
    build: .
    image: user-management-service:latest
    container_name: user-management-service
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 28859013

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://localhost:8761/eureka/"

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    depends_on:
      - postgres
      - zookeeper
      - kafka
    networks:
      - user-management-net

  # --- PostgreSQL ---
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_DB: Sensa_User_Management_Service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 28859013
    ports:
      - "5432:5432"
    networks:
      - user-management-net

  # --- Zookeeper ---
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - user-management-net

  # --- Kafka ---
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - user-management-net

networks:
  user-management-net:
    driver: bridge
