spring:
  application:
    name: message-delivery-service

  kafka:
    bootstrap-servers: localhost:9092
    client-id: message-delivery-service
    topics:
      notification:
        message-delivery-service-to-notification-service

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/


services:
  user-management-service: http://localhost:8000
  notification-service: http://localhost:8004

server:
  port: 8005
